# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'FireBaseDemo8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseDemo8
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end
