# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'FirebaseDemo9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseDemo9
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'

end
